apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  containers:
  - env:
    - name: MYSQL_USER
      value: user
    - name: MYSQL_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: db
      image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_mariadb:latest
    imagePullPolicy: Always
    name: mariadb
    ports:
    - containerPort: 3306
      name: dbport
      protocol: TCP
  hostname: mariadb
